# Replace the text below to customize your site
site_name: Connor Cruz Portfolio
site_description: Project documentation for Connor Cruz
site_author: Connor Cruz
copyright: Copyright 2025 Connor Cruz - Creative Commons Attribution Non Commercial

site_url: https://connorfcruz.github.io/cruz-connor-portfolio/

theme: material
  # name: null
  # custom_dir: mkdocs_windmill
  # palette:
  #   # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  #   primary: deep
  #   accent: indigo
  # font:
  #   # See available fonts at https://fonts.google.com/
  #   text: Ubuntu
  #   code: Ubuntu Mono
  # icon:
  #   logo: material/school
  # favicon: images/favicon.svg
  # features:
  #   - navigation.tabs
  #   - navigation.instant

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true