name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write    # 👈 allow pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material mkdocs-audio
      - run: mkdocs build --strict
      - run: mkdocs gh-deploy --force
